#!/usr/bin/env python3

import graphlib
import asyncio
from initializer import initializer

from fw.apps import Pipeline
        

pipeline = Pipeline()

pipeline.FakeHtSrc(
           name = "fake"
         ).FakeTransform(
           name = "transform"
         ).FakeOutput(
           name = "out"
         )

pipeline.run()
