#!/usr/bin/env python3
from fw.apps import Pipeline
        

pipeline = Pipeline()

#
#          -------
#         | src   |
#          -------       (example of connecting src pad twice)
#         /       \------------------
#     H1 /         \ L1              \ L1
#   ----------      -----------       ------------
#  | H1 trans |    | L1 trans  |     | L1 trans 2 |
#   ----------      -----------       ------------
#     H1 \        / L1                    |
#        -------                       --------
#       | sink  |                     | sink 2 |
#        -------                       --------
#


pipeline.FakeHtSrc(
           name = "fake",
           channels = ("H1","L1"),
         ).FakeTransform(
           name = "H1 transform", src_pad_name = "fake:H1:src"
         ).FakeOutput(
           name = "out",
           channels = ("H1","L1"),
           sink_pad_name = "out:H1:sink"
         )

pipeline.FakeTransform(
           name = "L1 transform",
           src_pad_name = "fake:L1:src",
         ).link(
           src_pad_name = "L1 transform:src",
           sink_pad_name = "out:L1:sink"
         )

pipeline.FakeTransform(
           name = "L1 transform 2",
           src_pad_name = "fake:L1:src",
           head = "fake"
         ).FakeOutput(
           name = "out2",
           channels = ("L1",)
         )

pipeline.run()
