#!/usr/bin/env python3
from fw.apps import Pipeline
        

pipeline = Pipeline()

pipeline.FakeHtSrc(
           name = "fake"
         ).FakeTransform(
           name = "transform"
         ).FakeOutput(
           name = "out"
         )

pipeline.run()
